spring.application.name=SmartGuardian

# Database Configuration
# updated to match the running dev container database
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
smartguardian.app.jwtSecret=${JWT_SECRET}
smartguardian.app.jwtExpirationMs=86400000 // 1 day

# Fitbit
fitbit.client-id=${FITBIT_CLIENT_ID}
fitbit.client-secret=${FITBIT_CLIENT_SECRET}
fitbit.redirect-uri=${FITBIT_REDIRECT_URI}

