spring.application.name=Health App Backend

# Database Configuration
# updated to match the running dev container database
spring.datasource.url=jdbc:postgresql://localhost:5432/healthapp
spring.datasource.username=secureuser
spring.datasource.password=securepassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
securehealthapp.app.jwtSecret=bXlTZWNyZXRLZXk=
securehealthapp.app.jwtExpirationMs=86400000